dist: bionic  # 系统
language: node_js # 语言环境
node_js:
  - 12.16.2 # node版本
cache: npm
install:
  - npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $deploy_secret # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  target_branch: deploy
  local_dir: /dist