deploy:
  provider: pages
  skip_cleanup: true
  github_token: $deploy_secret # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  target_branch: deploy
  local_dir: /dist