dist: bionic  # 系统
language: node_js # 语言环境
node_js:
  - 12.16.2 # node版本
cache: npm
install:
  - npm install
script: npm run build
branch:
  only:
    - master
git:
  quite: true
  depth: 1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $DEPLOY
  keep_history: true
  on:
    branch: master
  local_dir: ./dist/